### ISSUE TITLE
Syntax file not in repo

### ISSUE THREAD

**Issue by mojo2012** [StarHack/sublime-impex-syntax#1]
hey, the readme refers to a file, that is not present. The *package file seems not to be the right one, or it can't be installed by simply copying into the *User* folder

**Comment by StarHack** [comment]
@mojo2012 my sincere apologies for the late response, I didn't receive an email notification regarding the new issue. I was referring to the file `impex.sublime-package` which was written in the YAML 1.2 format - it's part of the repository. I just checked back and it should work properly: https://i.imgur.com/7nFrbkg.png

Sublime Text 3 Build 3126 on MacOS.
